server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: people-system-realm.json
  theme:
    staticMaxAge: 2592000
    cacheTemplates: false
    cacheThemes: false
    custom: custom-theme
